name: CI - Ejecucion de Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Cambia '17' por '21' aquí
      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # <--- CAMBIAR A 21
          distribution: 'temurin'
          cache: 'maven'

      # 2. Asegúrate de que el working-directory esté correcto (si aún no lo está)
      - name: Run Unit Tests Only
        run: mvn test -Dsurefire.excludeJUnit5Engines=cucumber
        working-directory: backend/